### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by j-koziel** [j-koziel/titanic-fitness#1]
# TODO
- [x] Add sitemap
- [x] Complete about page
- [x] Complete gym locations page
- [x] Complete subscriptions page
- [x] Create meal plans database
- [x] Use meal api to get meals
- [x] Make form fields required in history
- [x] fix progress form
